export interface LlmsEntry {
  title: string;
  url: string;
  summary: string;
}

export function buildLlmsTxt(siteUrl: string, entries: LlmsEntry[]): string {
  const hostname = new URL(siteUrl).hostname;
  return [
    `# ${hostname} – GEO Content Directory`,
    '',
    '> Machine-readable factual directory for AI assistants and answer engines.',
    '> Generated by innotek-seo CLI — https://innotekseoai.com',
    '',
    ...entries.map((e) => `- [${e.title}](${e.url}): ${e.summary}`),
    '',
  ].join('\n');
}
